restore java8 compatability
jenkinsci/trilead-ssh2 pull request #106
Opened 2022-08-04 11:09 UTC by jtnord

See [JENKINS-69229](https://issues.jenkins-ci.org/browse/JENKINS-69229).

revert the parent update that enforces java11 and does not give a nice way to go back to java 11.

with this version of the parent spotbugs reports a *lot* of issues and as we are fine with them as is - just disable spotbugs for the moment.

maven-enforcer-plugin is checking the bytecode of all the libraries, whilst it excludes `jbcrypt` this is version 1.0.0 that has been included for over 5 years so this should not be causing any new issues.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Appropriate autotests or explanation to why this change has no tests

2022-08-04 11:22 UTC, jglick requested changes
https://github.com/jenkinsci/trilead-ssh2/blob/a4b1c4ff9e4e41cd9891acdb535126dbeb40f868/.github/dependabot.yml#L3-L6 nothing is preventing this from being undone.

2022-08-04 11:23 UTC, jtnord commented
> 

I would expect a human review to be obvious as the diff will show

`        <!-- do not upgrade the parent until we want to force everyone to java11 -->` directly above the line being changed.

2022-08-04 14:06 UTC, kuisathaverat commented
I do not see a strong reason to restore Java 8 compatibility, in less than 30 days Jenkins will not support it.

2022-08-04 15:44 UTC, ericndunn commented
> I do not see a strong reason to restore Java 8 compatibility, in less than 30 days Jenkins will not support it.

We have some Legacy support that requires Java8 connections for Jenkins ssh-slave plugins

2022-08-04 16:04 UTC, jglick commented
> We have some Legacy support that requires Java8 connections

And nothing is stopping you from running the current plugin version on your server, which is presumably older than 2.357 which dropped Java 8 support. This issue is about new plugin releases.

2022-08-04 16:19 UTC, kuisathaverat commented
> We have some Legacy support that requires Java8 connections for Jenkins ssh-slave plugins

Jenkins core >=2.357 will require Java 11. If you use trilead-api >= 1.71.v9e7860a_67a_df, the agents connected to this Jenkins must use Java 11 too. The recommendation is to use the same JDK on the Jenkins Controller and Jenkins Agents.
If your requirement to use Java 8 is to compile and test your software, you can still do it. The JDK you use to run the remoting process on your Agents could not be the same you use to build and test.

2022-09-08 08:50 UTC, kuisathaverat commented
I think this PR can be closed

2022-09-08 19:49 UTC, Elisedlund-ericsson commented
@kuisathaverat  there have been tons of complaints within my company that the new version required JDK11 while many were still stuck on java 8 (atleast for a short while more) 
I had to finally revert to an older version of trilead to restore java 8 compatibility in my library that uses trilead. 
and then tell the users of my library to override version to the latest version of trilead if they needed #93 
So far none that were stuck on java 8 and needing #93

2022-09-08 22:15 UTC, jglick commented
Someone outside Jenkins is still using Trilead? It should be considered deprecated.

2022-09-09 06:50 UTC, slandelle commented
@jglick We're using `com.trilead.ssh2.crypto.PEMDecoder` to decode OPENSSH private keys. Couldn't figure out how to do it with BouncyCastle so far.

2022-09-09 06:51 UTC, Elisedlund-ericsson commented
@jglick so what would you recommend instead? 
I think you are selling Trilead short.
We have lookinto switching before to other libraries such as Jsch, sshj before, they  which possibly won on stuff such as easy to use API but did not support all the same authentication protocols or algorithms and/or had lower performance. 

mina-sshd was probably not fully ready at that point but is probably good enough today.
What about Trilead caused you consider it be deprecated and not good enough to be used? 

We wrap Trilead in our own API and use it to connect to huge amount of ssh servers of different kinds and it has always worked fantastic for our endusers, All error blamed on Trilead has almost always been user error, crappy ssh server or network setup. 
We have been able contribute to Trilead for all the issues we have had, some examples #7 #38 #40 #44 #60 #93 (we probably added almost all the new MAC and KEX over the years) 
 
Swapping ssh library would mostly be a headache for us, and would only cause toons of minor integration issues for our users, like the disconnect taking 50ms longer or stupid stuff like that.

2022-09-09 08:03 UTC, kuisathaverat commented
I am porting the SSH build agent to mina-sshd, it is nice than Trilead at API level and is well documented. I also have test [connectbot](https://github.com/connectbot/sshlib) that was my first option to shade that library replacing only a few classes that are Jenkins implementations, was fine too. Finally, I chose Apache Mina SSHD because the Apache foundation is behind and is well documented.

2024-07-13 09:42 UTC, jtnord commented
> @jglick We're using `com.trilead.ssh2.crypto.PEMDecoder` to decode OPENSSH private keys. Couldn't figure out how to do it with BouncyCastle so far.

A bit late but see https://github.com/bcgit/bc-java/blob/main/prov/src/test/java/org/bouncycastle/jce/provider/test/OpenSSHSpecTests.java

2024-07-13 09:42 UTC, closed without merging